sumocoders/application-skeleton

.gitlab-ci.yml, composer.json
Added a new job (which may fail) in `.gitlab-ci.yml`. The job will check all files for the words:
- FIXME
- TODO
- HACK
- REVIEW
- QUESTION
- TEMP
If an occurrence is found it will be shown in the merge request as an issue. I reused the JUnit reporting as it is already in place for reporting vulnerability scanning.
In essence this is nothing more than a `grep` command which is is processed by the converter tool I wrote earlier to convert JSON to XML.
This solves: https://app.activecollab.com/108877/my-work?modal=Task-64424-45
=> Check for todo's

src/Skeleton/PostCreateProject.php
See https://app.activecollab.com/108877/projects/533/tasks/108044
=> 134 import js

.gitlab-ci.yml, composer.json, src/Skeleton/PostCreateProject.php
As [SensioLabs Security Checker](https://github.com/sensiolabs/security-checker) is deprecated.
I replaced it with [Local PHP Security Checker](https://github.com/fabpot/local-php-security-checker/tree/v1.0.0)
Should fix https://app.activecollab.com/108877/projects/533/tasks/114679
=> 135 disable sensiolabs security checker

src/Skeleton/PostCreateProject.php
Symfony has changed it's locale prefix config https://symfony.com/doc/current/routing.html#localized-routes-i18n
=> Don't add prefix for en routes

src/Skeleton/PostCreateProject.php
Fixes https://github.com/sumocoders/application-skeleton/issues/20
=> Enable the Vue loader in our webpack config

src/Skeleton/PostCreateProject.php
Adds global breadcrumbs variable to twig
**Can only be merged when https://github.com/sumocoders/FrameworkCoreBundle/pull/53#event-4540270109 is merged!**
=> Add global breadcrumbs

.env.test, .gitlab-ci.yml, README.md, composer.json, composer.lock, phpunit.xml.dist, src/Skeleton/PostCreateProject.php, symfony.lock, tests/PagesAreFoundTest.php, tests/bootstrap.php
internal ref https://app.activecollab.com/108877/reports/team-timeline?modal=Task-56569-533
=> 112 test suite

.gitlab-ci.yml
This PR makes the CI/CD pipeline work again. More particularly the PHPUnit tests.
An example pipeline can be seen on: https://git.sumocoders.be/tijs/skeleton/-/pipelines/55404
This resolves https://app.activecollab.com/108877/projects/533?modal=Task-123878-533
=> Bugfix unit tests

src/Skeleton/PostCreateProject.php
Symfony 5.3 added new config to the bottom of framework.yml so we have to adjust our modifications.
=> Fix framework configuration

composer.json, src/Skeleton/PostCreateProject.php
Is required for https://github.com/sumocoders/FrameworkCoreBundle/pull/77 to work out of the box
=> Generate a 64 bit key for use with libsodium in our base .env

src/Skeleton/PostCreateProject.php
There is an app.css file in there we don't use.
=> Fix app.js

src/Skeleton/PostCreateProject.php
=> Refactor old Deployer ->local method to new ->runLocally

.gitlab-ci.yml
Only scan packages that are part of the dependencies, not devDependencies
=> Only scan real dependencies

src/Skeleton/PostCreateProject.php
=> Remove jQuery autoprovide in webpack config

src/Skeleton/PostCreateProject.php
Merge after https://github.com/sumocoders/FrameworkStylePackage/pull/96/files and https://github.com/sumocoders/FrameworkCoreBundle/pull/114/files
=> Enable the bazinga command in the webpack configuration

.gitlab-ci.yml, src/Skeleton/PostCreateProject.php
Replace nvm with volta.
Make sure https://git.sumocoders.be/sumocoders/docker/-/merge_requests/34 is merged before merging this PR.
=> Use volta instead of nvm

src/Skeleton/PostCreateProject.php
Update framework init in PostCreateProject.php - for use with frameworkstylepackage v3
=> Update framework init in PostCreateProject.php

docker-compose.override.yml, docker-compose.yml
Removes unnecessary web container en defaults mysql to 5.7
=> Use mysql 5.7 by default and remove web container

src/Skeleton/PostCreateProject.php
Fixes the broken webpack configuration
=> 290 page title fix pipelines

.twig-cs-fixer.dist.php, composer.json
Use TwigCsFixer instead of TwigCs
=> Require vincentlanglet/twig-cs-fixer

composer.json, src/Skeleton/PostCreateProject.php
- Setup rotating file for monolog logging
- Fix page_title global variable for twig
- Update sentry to v5
=> Fix post create script

src/Skeleton/PostCreateProject.php
* sass compilation warnings from dependencies will not be shown anymore
* Use `sass-embedded` for the sass compilation 
* disable build notifications
=> Webpack optimalisations

scripts/test.sh, src/Skeleton/PostCreateProject.php
Add DEFAULT_URI env var to config
=> Routing DEFAULT_URI

.crontab
This is related to https://github.com/tijsverkoyen/deployer-sumo/pull/38
=> Add default crontab file

src/Skeleton/PostCreateProject.php
Internal link: https://app.activecollab.com/108877/reports/assignments?modal=Task-203863-533
=> Audit trail monolog config

.gitlab-ci.yml
https://github.com/fabpot/local-php-security-checker?tab=readme-ov-file#local-php-security-checker
=> Remove PHP Security checker

composer.json, scripts/assets/js/app.js, scripts/assets/js/bootstrap.js, src/Skeleton/PostCreateProject.php
Convert our JS to stimulus controllersWorks together with changes to our https://github.com/sumocoders/FrameworkCoreBundle/pull/171
=> 319 stimulus

src/Skeleton/PostCreateProject.php
See https://github.com/sumocoders/FrameworkCoreBundle/pull/182
=> Add AJAX client

composer.json
Altough it is a major release it is backwards compatible
=> Update phpcs-gitlab dependency version to 2.0
