sumocoders/application-skeleton

scripts/assets/app.scss

These files are already imported in our style package, so they're
redundant here.
if I'm wrong about this feel free to tell me. The file that we import through the skeleton is this one: https://github.com/sumocoders/FrameworkStylePackage/blob/master/src/sass/style.scss, which in turns references the bootstrap variables and functions.

Remove redundant bootstrap import

---

.gitlab-ci.yml

This should improve the total time needed for running the pipeline.
The composer packages are now install before everything else and cached, so no need to install them again and again in each job.
Also our images have composer installed, so there is no need to install composer ourself in a job.

Improve jobs

---

src/Skeleton/PostCreateProject.php

We don't want to use configureBabelPresetEnv, but configureBabel instead.
For more information see https://app.activecollab.com/108877/projects/533/tasks/96087

Fixing an IE11 bug

---

composer.json
src/Skeleton/PostCreateProject.php

It seems like JsTranslationBundle v3 is not compatible with Symfony 5, so bumped it to v4
Alos, when running the command something fails while running `bin/console bazinga:js-translation:dump public/build --format=json --merge-domains`, so I commented it for now.
Should fix: https://app.activecollab.com/108877/projects/533/tasks/95254

Fix issue with js translation bundle

---

.stylelintignore

The generated files, svg's are mostly files we don't control, so there is no
use to check them.

Ignore generated files when running stylelint

---

.gitlab-ci.yml
composer.json

It uses [friendsoftwig/twigcs](https://github.com/friendsoftwig/twigcs), which
validates for the official coding standard of Twig.
An example of the output: https://git.sumocoders.be/sumocoders/wasewind-app/-/jobs/141925

Job that checks coding standards for Twig templates

---

src/Skeleton/PostCreateProject.php

Symfony listens for these errors using the kernel.exception event and handles them accordingly
(redirect to login, show 404, etc..) but even when handled, they still get thrown so Sentry
logs them. This ends up flooding our Sentry logs with errors that don't mean anything.

Ignore common Sentry errors

---

src/Skeleton/PostCreateProject.php

This will be used by the inline_css filter to locate the built version of our mail.css file. We have to read this file using the Twig source() function, which by default only reads from the default Twig path: /templates.
Usually source() is only intended for loading templates, as the asset() and webpack_encore_link_tag() methods exist to load stylesheets inside templates, but since both email clients and the inline_css extension don't actually resolve stylesheet URLs, we need to use this hack-y method to get the raw content of the CSS file and pass it to the inline_css extension manually.

Register a Twig path for our public folder by default.

---

src/Skeleton/PostCreateProject.php

The default twig.yaml config used to be:
```
twig:
default_path: '%kernel.project_dir%/templates'
```
which meant we could just append our changes to the end of the file. But after 5.3 (or with the new Panther test suite), it's:
```
twig:
default_path: '%kernel.project_dir%/templates'
when@test:
twig:
strict_variables: true
```
which breaks the current set-up. This PR inserts our changes on the next line after `twig:`, which produces a valid yaml config file.

Update the twig configuration with the new 5.3 added test config

---

.gitlab-ci.yml

As the stages Code quality, Dependency scanning and Test are just in place for
our own piece of mind the jobs can be run without the need of the stage to be
finished.
The `needs` keyword allows us to specify which jobs should be finished before
starting the jobs. In essence this is the same for all jobs: the building of
the cache, which is used by all other jobs.
See https://docs.gitlab.com/ee/ci/yaml/index.html#needs for more information.

Use the `needs` keyword to speed up the pipeline

---

src/Skeleton/PostCreateProject.php

After changing the twig config, our first added line is on the same line as `twig:` which breaks the yaml config

Fix twig.yaml

---

src/Skeleton/PostCreateProject.php

Error from `npm install` during initial composer create-project.
```
[webpack-cli] Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.
- options should be one of these:
object { resourceRegExp, contextRegExp? } | object { checkResource }
Details:
* options misses the property 'resourceRegExp'. Should be:
RegExp
-> A RegExp to test the request against.
* options misses the property 'checkResource'. Should be:
function
-> A filter function for resource and context.
```
Fix from docs:
```
new webpack.IgnorePlugin({resourceRegExp, contextRegExp});
// old way, deprecated in webpack v5
new webpack.IgnorePlugin(resourceRegExp, [contextRegExp]);
```
Exact match with new syntax from Webpack 5 docs:
```
new webpack.IgnorePlugin({ …
```

Refactor IgnorePlugin to Webpack 5 syntax

---

.stylelintignore

In new framework projects there shouldn't be any CSS/Sass outside of the assets
and/or public/build folder. Right now Stylelint will also run on all of our PHP files.

Add the src folder to the Stylelint ignore

---

.gitlab-ci.yml

Chromium on Debian is only at v97, Google Driver release is at 98

Lock ChromeDriver to v97

---

composer.json

Starting from  July 2022 unlisted plugins will not be able to execute code.
See https://getcomposer.org/doc/06-config.md#allow-plugins for more information

Allow some plugins to execute code

---

.gitlab-ci.yml

As discusses in the DevMeeting the `phpcs` and `phpstan` jobs should fail if there are issues.

phpstan and phpcs can't fail

---

deploy.php

Till this point the default of 10 was used, which is a bit much and unneeded.

Limit the number of releases that should be kept to 3

---

composer.json

We're on PHP8.1, so we should use the matching Flex version

Bump symfony/flex to the 2.0 release

---

src/Skeleton/PostCreateProject.php

As of Symfony 6, there is a when@prod prefix in the default sentry.yaml file that Symfony generates. To accommodate this, we have to add another tab to the indentation of our custom Sentry config.

Change the indentation of the sentry.yaml configuration file

---

composer.json

We had to set this to beta for the Deployer 7 beta, but this is no longer valid

Bump minimum dependency stability

---

src/Skeleton/PostCreateProject.php

We added a custom `content()` Twig extension in the core bundle to handle this (and fix a bug with twig caching our assets). This config is no longer necessary.
To be merged with https://github.com/sumocoders/FrameworkCoreBundle/pull/119

Remove the public folder from the Twig path

---

src/Skeleton/PostCreateProject.php

Sending the baggage header might result in errors from external APIs and can potentially leak private data.
This limits the trace_propagation_targets to only the current domain. An empty array (the default when not set) is treated as all hosts are allow listed.
See this PR for additional info: https://github.com/getsentry/sentry-php/pull/1396

Do not send sentry traces to third-parties

---

.gitlab-ci.yml

Add `composer audit` into our jobs.
<strike>I don't think it has a huge advantage over the `local-security-checker`</strike>. But it can't hurt to have it run also.
After reading some more it seems that `composer audit` use the same "database" as `local-security-checker`, but the GitHub advisory database also.
More information: https://php.watch/articles/composer-audit

Composer audit

---

.gitlab-ci.yml

Use npm ci instead off npm install.
https://cheatsheetseries.owasp.org/cheatsheets/NPM_Security_Cheat_Sheet.html

Use npm ci instead off npm install

---

.gitlab-ci.yml

Since version 2.1.0 of local-php-security-checker, the name of the prebuild binary changed (https://github.com/fabpot/local-php-security-checker/releases).

Fix local security checker download url

---

docker-compose.yml
src/Skeleton/PostCreateProject.php

https://app.activecollab.com/108877/my-work?modal=Task-208182-533
Don't expose Symfony Server magic ENV variables into our database service.
Remove `doctrine/doctrine-bundle` and `symfony/mailer` docker stuff that may be added automatically.

332 docker config

---

src/Skeleton/PostCreateProject.php

The original code removed some code which made the config invalid:
FROM:
```
when@test:
doctrine:
dbal:
dbname_suffix: '_test%env(default::TEST_TOKEN)%'
when@prod:
doctrine:
orm:
auto_generate_proxy_classes: false
proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
query_cache_driver:
type: pool
pool: doctrine.system_cache_pool
result_cache_driver:
type: pool
pool: doctrine.result_cache_pool
```
TO (BROKEN):
```
when@test:
doctrine:
dbal:
dbname_suffix: '%env(string:default::TEST_TOKEN)%'
query_cache_driver:
type: pool
pool: doctrine.system_cache_pool
result_cache_driver:
type: pool
pool: doctrine.result_cache_pool
```
TO (FIXED):
```
when@test:
doctrine:
dbal:
dbname_suffix: '%env(string:default::TEST_TOKEN)%'
when@prod:
doctrine:
orm:
auto_generate_proxy_classes: false
proxy_dir: …
```

Fix doctrine config
